Import Libraries

In [3]:
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras import optimizers
import nibabel as nib
import numpy as np
import os
import nibabel as nib
from skimage.transform import resize
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

Data Preprocessing

In [4]:
def load_data(case_id):
    image_path = f"C:\\Users\\shiva\\Downloads\\HYPODENSITY-DATA\\{case_id}\\{case_id}_NCCT.nii.gz"
    mask_path = f"C:\\Users\\shiva\\Downloads\\HYPODENSITY-DATA\\{case_id}\\{case_id}_ROI.nii.gz"
    #C:\Users\shiva\Downloads\HYPODENSITY-DATA\ProxmedImg006\ProxmedImg006_NCCT.nii.gz

    image_data = nib.load(image_path).get_fdata()
    mask_data = nib.load(mask_path).get_fdata()

    # Normalize the image data
    image_data = (image_data - np.min(image_data)) / (np.max(image_data) - np.min(image_data))

    return image_data, mask_data

def preprocess_data(image_data, mask_data):
    # You can apply additional preprocessing steps here
    return image_data, mask_data


In [5]:
import nibabel as nib

# Load the NIfTI image
nifti_img = nib.load(r'C:\Users\shiva\Downloads\HYPODENSITY-DATA\ProxmedImg006\ProxmedImg006_NCCT.nii.gz')

# Get the image data array
data = nifti_img.get_fdata()

# Get the dimensions of the 3D image
dimensions = data.shape

# Print the dimensions
print("Dimensions:", dimensions)

Dimensions: (512, 512, 58)


Build the model

In [6]:
from tensorflow.keras import layers, models
from tensorflow.keras.utils import to_categorical

def create_model(input_shape):
    model = models.Sequential()

    # Adjust the parameters in Conv3D layers and add more layers as needed
    model.add(layers.Conv3D(64, (3, 3, 3), activation='relu', input_shape=input_shape, padding='same'))
    model.add(layers.MaxPooling3D((2, 2, 2), padding='same'))

    # Add more layers as needed
    

    model.add(layers.Conv3D(1, (1, 1, 1), activation='sigmoid', padding='same'))  # Assuming binary segmentation

    return model

# Adjust input_shape based on your actual image dimensions
input_shape = (512, 512, 58, 1)
model = create_model(input_shape)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


Trainig The model

In [7]:
def train_model(model, train_data, train_labels, epochs, batch_size):
    # Compile the model before training
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    
    
    # Train the model
    model.fit(train_data, train_labels, epochs=epochs, batch_size=batch_size, validation_split=0.2)


Model Evaluation

In [8]:
def evaluate_model(model, test_data, test_labels):
    evaluation = model.evaluate(test_data, test_labels)
    print("Test Loss:", evaluation[0])
    print("Test Accuracy:", evaluation[1])


inference

In [9]:
def predict(model, input_data):
    predictions = model.predict(input_data)
    return predictions


Putting All together



# Assuming you have a directory containing the NCCT images and corresponding ROI masks
data_dir = r"C:\Users\shiva\Downloads\HYPODENSITY-DATA"
all_cases = os.listdir(data_dir)

# Load images and masks
images = []
masks = []

for case_id in all_cases:
    #img_path = os.path.join(f"C:\\Users\\shiva\\Downloads\\HYPODENSITY-DATA\\{case_id}", f"{case_id}_NCCT.nii.gz")
    #mask_path = os.path.join(f"C:\\Users\\shiva\\Downloads\\HYPODENSITY-DATA\\{case_id}", f"{case_id}_ROI.nii.gz")
    
    image_data, mask_data = load_data(case_id)
    image_data, mask_data = preprocess_data(image_data, mask_data)

    
    #images.append(img_path)
    #masks.append(mask_path)


# Expand dimensions for the channel axis

#image_data = np.expand_dims(image_data, axis=1)
# Build the model
model = create_model(input_shape=image_data.shape[0:])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model,image_data[0],'\n',mask_data[0])
# Train the model
train_model(Sequential(),image_data, mask_data, epochs=10, batch_size=4)

# Evaluate the model (optional)
# evaluate_model(model, test_data, test_labels)

# Make predictions on new data
#new_data = load_and_preprocess_new_data(r"C:\Users\shiva\Downloads\HYPODENSITY-DATA\ProxmedImg014")
#new_data = np.expand_dims(new_data, axis=-1)
#predictions = predict(model, new_data)







In [29]:


# Assuming you have a directory containing the NCCT images and corresponding ROI masks
data_dir = r"C:\Users\shiva\Downloads\HYPODENSITY-DATA"
all_cases = os.listdir(data_dir)

# Load images and masks
images = []
masks = []

for case_id in all_cases:
    #img_path = os.path.join(f"C:\\Users\\shiva\\Downloads\\HYPODENSITY-DATA\\{case_id}", f"{case_id}_NCCT.nii.gz")
    #mask_path = os.path.join(f"C:\\Users\\shiva\\Downloads\\HYPODENSITY-DATA\\{case_id}", f"{case_id}_ROI.nii.gz")
    
    image_data, mask_data = load_data(case_id)
    image_data, mask_data = preprocess_data(image_data, mask_data)

    
   
X_train, X_test, y_train, y_test = train_test_split(image_data, mask_data, test_size=0.2, random_state=42)



print(X_train,y_train)


[[[0.01115242 0.00966543 0.00768278 ... 0.00594796 0.00718711 0.00619579]
  [0.01115242 0.01040892 0.00768278 ... 0.00594796 0.00693928 0.00594796]
  [0.01065675 0.01115242 0.00842627 ... 0.00619579 0.00644362 0.00570012]
  ...
  [0.02503098 0.0260223  0.02503098 ... 0.03172243 0.01239157 0.01412639]
  [0.02973978 0.02230483 0.02775713 ... 0.03048327 0.01982652 0.0173482 ]
  [0.0394052  0.01883519 0.03023544 ... 0.03048327 0.02949195 0.02651797]]

 [[0.00892193 0.00793061 0.00743494 ... 0.00570012 0.00619579 0.00545229]
  [0.0086741  0.00793061 0.00718711 ... 0.00545229 0.00619579 0.00545229]
  [0.0086741  0.00793061 0.00768278 ... 0.00570012 0.00594796 0.00570012]
  ...
  [0.03246592 0.01982652 0.03965304 ... 0.0267658  0.02850062 0.02726146]
  [0.0307311  0.01685254 0.04560099 ... 0.02255266 0.02304833 0.02354399]
  [0.02825279 0.01288724 0.04337051 ... 0.02032218 0.02032218 0.02106568]]

 [[0.00693928 0.00669145 0.00693928 ... 0.00570012 0.00644362 0.00619579]
  [0.00669145 0.006939

In [14]:
def build_unet_model(input_shape):
    inputs = tf.keras.Input(shape=input_shape)

    # Encoder
    conv1 = layers.Conv2D(64, 3, activation='relu', padding='same')(inputs)
    conv1 = layers.Conv2D(64, 3, activation='relu', padding='same')(conv1)
    pool1 = layers.MaxPooling2D(pool_size=(2, 2))(conv1)

    # Decoder
    conv2 = layers.Conv2D(128, 3, activation='relu', padding='same')(pool1)
    conv2 = layers.Conv2D(128, 3, activation='relu', padding='same')(conv2)
    up1 = layers.UpSampling2D(size=(2, 2))(conv2)

    # Output layer
    outputs = layers.Conv2D(1, 1, activation='sigmoid')(up1)

    model = models.Model(inputs=inputs, outputs=outputs)
    return model

# Build the model
input_shape = (512,512,58)  # Replace with your image dimensions
model = build_unet_model(input_shape)
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])


In [25]:
y_test.shape

(103, 512, 35)

In [30]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Flatten

# Assuming you have X_train, X_test, y_train, and y_test with the specified shapes

# Create a simple neural network model
model = Sequential()
model.add(Flatten(input_shape=(512, 35)))  # Flatten the 3D input to 2D
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))  # Assuming binary classification, adjust for your task

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=32)


Epoch 1/10


ValueError: in user code:

    File "c:\Users\shiva\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1401, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\shiva\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1384, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\shiva\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1373, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\shiva\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1151, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "c:\Users\shiva\anaconda3\Lib\site-packages\keras\src\engine\training.py", line 1209, in compute_loss
        return self.compiled_loss(
    File "c:\Users\shiva\anaconda3\Lib\site-packages\keras\src\engine\compile_utils.py", line 277, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "c:\Users\shiva\anaconda3\Lib\site-packages\keras\src\losses.py", line 143, in __call__
        losses = call_fn(y_true, y_pred)
    File "c:\Users\shiva\anaconda3\Lib\site-packages\keras\src\losses.py", line 270, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "c:\Users\shiva\anaconda3\Lib\site-packages\keras\src\losses.py", line 2532, in binary_crossentropy
        backend.binary_crossentropy(y_true, y_pred, from_logits=from_logits),
    File "c:\Users\shiva\anaconda3\Lib\site-packages\keras\src\backend.py", line 5822, in binary_crossentropy
        return tf.nn.sigmoid_cross_entropy_with_logits(

    ValueError: `logits` and `labels` must have the same shape, received ((None, 1) vs (None, 512, 35)).


In [27]:
# Assuming you have already trained the model using the code provided in the previous response

# Evaluate the model on the test data
evaluation_results = model.evaluate(X_test, y_test)

# Print the evaluation results
print("Test Loss:", evaluation_results[0])
print("Test Accuracy:", evaluation_results[1])


4/4 [==============================] - 0s 8ms/step - loss: 0.7348 - accuracy: 0.4369
Test Loss: 0.7347683906555176
Test Accuracy: 0.43689319491386414
